pipeline {
    agent any

    environment {
        PATH = "/usr/bin/dotnet:$PATH"  // Ajouter dotnet à votre PATH si ce n'est pas déjà fait
    }


    stages {
        stage('Checkout') {
            steps {
                // Cloner votre dépôt Git
                git branch: 'main', url: 'https://github.com/ryajbar75/projetJenkins.git'
            }
        }

        stage('Build') {
            steps {
                // Construire le projet .NET
                script {
                    sh 'dotnet build'
                }
            }
        }

        stage('Test') {
            steps {
                // Exécuter les tests avec dotnet
                script {
                    sh 'dotnet test'
                }
            }
        }

        stage('Publish') {
            steps {
                // Publier le projet .NET
                script {
                    sh 'dotnet publish -c Release -o out'
                }
            }
        }
    }
}
