pipeline {
    agent any

    environment {
        PATH = "/usr/bin/dotnet:$PATH"  // Ajouter dotnet à votre PATH si ce n'est pas déjà fait
        DOCKER_IMAGE_NAME = "gestion-bib" // Nom de l'image Docker à utiliser
        DOCKER_TAG = "2.21.5" // Tag de l'image Docker
        REGISTRY = "docker.io" // Docker registry, changez selon votre besoin
        DOCKER_CREDENTIALS_ID = "dockerhub-credentials" // ID des credentials pour Docker Hub
    }

    stages {
        stage('Checkout') {
            steps {
                // Cloner votre dépôt Git
                git credentialsId: 'jenkinsgit', branch: 'main', url: 'https://github.com/ryajbar75/projetJenkins.git'
            }
        }

        stage('Build') {
            steps {
                // Construire le projet .NET
                script {
                    sh 'dotnet build SQLi.Challenge/SQLi.Challenge.sln'
                }
            }
        }

        stage('Test') {
            steps {
                // Exécuter les tests avec dotnet
                script {
                    sh 'dotnet test SQLi.Challenge/SQLi.Challenge.sln'
                }
            }
        }

        stage('Publish') {
            steps {
                // Publier le projet .NET
                script {
                    sh 'dotnet publish SQLi.Challenge/SQLi.Challenge.sln -c Release -o out'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                // Construire l'image Docker
                script {
                    sh '''
                        docker build -t ${DOCKER_IMAGE_NAME}:${DOCKER_TAG} -f SQLi.Challenge/Dockerfile .
                    '''
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                // Push l'image Docker vers Docker Hub
                script {
                    withCredentials([usernamePassword(credentialsId: "${DOCKER_CREDENTIALS_ID}", usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                        sh '''
                            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
                            docker push ${DOCKER_IMAGE_NAME}:${DOCKER_TAG}
                        '''
                    }
                }
            }
        }
    }
}
